# Generated by Django 3.0.6 on 2020-05-21 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Transaction',
            new_name='Statement',
        ),
    ]
