# Generated by Django 3.0.6 on 2020-05-23 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0003_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statement',
            name='text',
            field=models.TextField(max_length=200),
        ),
    ]
