# Generated by Django 3.0.6 on 2020-05-23 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0005_auto_20200523_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statement',
            name='date_added',
        ),
        migrations.RemoveField(
            model_name='statement',
            name='text',
        ),
        migrations.AddField(
            model_name='statement',
            name='amount',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='statement',
            name='category',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='statement',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.AddField(
            model_name='statement',
            name='post_date',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='statement',
            name='transaction_date',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='statement',
            name='type',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
